// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/ccgobbles_server/ccgobbles_server.proto

package ccgobbles_server

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseType int32

const (
	ResponseType_SUCCESS ResponseType = 0
	ResponseType_FAILURE ResponseType = 1
)

var ResponseType_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
}

var ResponseType_value = map[string]int32{
	"SUCCESS": 0,
	"FAILURE": 1,
}

func (x ResponseType) Enum() *ResponseType {
	p := new(ResponseType)
	*p = x
	return p
}

func (x ResponseType) String() string {
	return proto.EnumName(ResponseType_name, int32(x))
}

func (x *ResponseType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResponseType_value, data, "ResponseType")
	if err != nil {
		return err
	}
	*x = ResponseType(value)
	return nil
}

func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{0}
}

type Address struct {
	StreetNumber         *string  `protobuf:"bytes,1,opt,name=streetNumber" json:"streetNumber,omitempty"`
	Street               *string  `protobuf:"bytes,2,opt,name=street" json:"street,omitempty"`
	City                 *string  `protobuf:"bytes,3,opt,name=city" json:"city,omitempty"`
	State                *string  `protobuf:"bytes,4,opt,name=state" json:"state,omitempty"`
	Zip                  *string  `protobuf:"bytes,5,opt,name=zip" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetStreetNumber() string {
	if m != nil && m.StreetNumber != nil {
		return *m.StreetNumber
	}
	return ""
}

func (m *Address) GetStreet() string {
	if m != nil && m.Street != nil {
		return *m.Street
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil && m.City != nil {
		return *m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

func (m *Address) GetZip() string {
	if m != nil && m.Zip != nil {
		return *m.Zip
	}
	return ""
}

type User struct {
	FirstName            *string  `protobuf:"bytes,1,opt,name=firstName" json:"firstName,omitempty"`
	LastName             *string  `protobuf:"bytes,2,opt,name=lastName" json:"lastName,omitempty"`
	Email                *string  `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Password             *string  `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`
	Address              *Address `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetFirstName() string {
	if m != nil && m.FirstName != nil {
		return *m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil && m.LastName != nil {
		return *m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *User) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type MenuItem struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Price                *float64 `protobuf:"fixed64,2,opt,name=price" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenuItem) Reset()         { *m = MenuItem{} }
func (m *MenuItem) String() string { return proto.CompactTextString(m) }
func (*MenuItem) ProtoMessage()    {}
func (*MenuItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{2}
}

func (m *MenuItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuItem.Unmarshal(m, b)
}
func (m *MenuItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuItem.Marshal(b, m, deterministic)
}
func (m *MenuItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuItem.Merge(m, src)
}
func (m *MenuItem) XXX_Size() int {
	return xxx_messageInfo_MenuItem.Size(m)
}
func (m *MenuItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuItem.DiscardUnknown(m)
}

var xxx_messageInfo_MenuItem proto.InternalMessageInfo

func (m *MenuItem) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *MenuItem) GetPrice() float64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

type Restaurant struct {
	Phone                *string     `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Email                *string     `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Name                 *string     `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Address              *Address    `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	Menuitem             []*MenuItem `protobuf:"bytes,5,rep,name=menuitem" json:"menuitem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Restaurant) Reset()         { *m = Restaurant{} }
func (m *Restaurant) String() string { return proto.CompactTextString(m) }
func (*Restaurant) ProtoMessage()    {}
func (*Restaurant) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{3}
}

func (m *Restaurant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restaurant.Unmarshal(m, b)
}
func (m *Restaurant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restaurant.Marshal(b, m, deterministic)
}
func (m *Restaurant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restaurant.Merge(m, src)
}
func (m *Restaurant) XXX_Size() int {
	return xxx_messageInfo_Restaurant.Size(m)
}
func (m *Restaurant) XXX_DiscardUnknown() {
	xxx_messageInfo_Restaurant.DiscardUnknown(m)
}

var xxx_messageInfo_Restaurant proto.InternalMessageInfo

func (m *Restaurant) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *Restaurant) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *Restaurant) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Restaurant) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Restaurant) GetMenuitem() []*MenuItem {
	if m != nil {
		return m.Menuitem
	}
	return nil
}

type Order struct {
	Email                *string  `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	RestId               *string  `protobuf:"bytes,2,opt,name=restId" json:"restId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{4}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *Order) GetRestId() string {
	if m != nil && m.RestId != nil {
		return *m.RestId
	}
	return ""
}

type OrderItem struct {
	MenuId               *string  `protobuf:"bytes,1,opt,name=menuId" json:"menuId,omitempty"`
	Quantity             *int64   `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderItem) Reset()         { *m = OrderItem{} }
func (m *OrderItem) String() string { return proto.CompactTextString(m) }
func (*OrderItem) ProtoMessage()    {}
func (*OrderItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{5}
}

func (m *OrderItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderItem.Unmarshal(m, b)
}
func (m *OrderItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderItem.Marshal(b, m, deterministic)
}
func (m *OrderItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderItem.Merge(m, src)
}
func (m *OrderItem) XXX_Size() int {
	return xxx_messageInfo_OrderItem.Size(m)
}
func (m *OrderItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderItem.DiscardUnknown(m)
}

var xxx_messageInfo_OrderItem proto.InternalMessageInfo

func (m *OrderItem) GetMenuId() string {
	if m != nil && m.MenuId != nil {
		return *m.MenuId
	}
	return ""
}

func (m *OrderItem) GetQuantity() int64 {
	if m != nil && m.Quantity != nil {
		return *m.Quantity
	}
	return 0
}

type RegisterUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{6}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterUserResponse struct {
	Response             *string  `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{7}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetResponse() string {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return ""
}

type LoginUserRequest struct {
	Email                *string  `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password             *string  `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserRequest) Reset()         { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()    {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{8}
}

func (m *LoginUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserRequest.Unmarshal(m, b)
}
func (m *LoginUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserRequest.Marshal(b, m, deterministic)
}
func (m *LoginUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserRequest.Merge(m, src)
}
func (m *LoginUserRequest) XXX_Size() int {
	return xxx_messageInfo_LoginUserRequest.Size(m)
}
func (m *LoginUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserRequest proto.InternalMessageInfo

func (m *LoginUserRequest) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *LoginUserRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type LoginUserResponse struct {
	Response             *bool    `protobuf:"varint,1,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserResponse) Reset()         { *m = LoginUserResponse{} }
func (m *LoginUserResponse) String() string { return proto.CompactTextString(m) }
func (*LoginUserResponse) ProtoMessage()    {}
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{9}
}

func (m *LoginUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserResponse.Unmarshal(m, b)
}
func (m *LoginUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserResponse.Marshal(b, m, deterministic)
}
func (m *LoginUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserResponse.Merge(m, src)
}
func (m *LoginUserResponse) XXX_Size() int {
	return xxx_messageInfo_LoginUserResponse.Size(m)
}
func (m *LoginUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserResponse proto.InternalMessageInfo

func (m *LoginUserResponse) GetResponse() bool {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return false
}

type UpdateUserRequest struct {
	OldEmail             *string  `protobuf:"bytes,1,opt,name=oldEmail" json:"oldEmail,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{10}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetOldEmail() string {
	if m != nil && m.OldEmail != nil {
		return *m.OldEmail
	}
	return ""
}

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	Response             *string  `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{11}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetResponse() string {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return ""
}

type DeleteUserRequest struct {
	Email                *string  `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{12}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

type DeleteUserResponse struct {
	Response             *string  `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{13}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetResponse() string {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return ""
}

type AddRestaurantRequest struct {
	Restaurant           *Restaurant `protobuf:"bytes,1,opt,name=restaurant" json:"restaurant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddRestaurantRequest) Reset()         { *m = AddRestaurantRequest{} }
func (m *AddRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*AddRestaurantRequest) ProtoMessage()    {}
func (*AddRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{14}
}

func (m *AddRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRestaurantRequest.Unmarshal(m, b)
}
func (m *AddRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *AddRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRestaurantRequest.Merge(m, src)
}
func (m *AddRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_AddRestaurantRequest.Size(m)
}
func (m *AddRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRestaurantRequest proto.InternalMessageInfo

func (m *AddRestaurantRequest) GetRestaurant() *Restaurant {
	if m != nil {
		return m.Restaurant
	}
	return nil
}

type AddRestaurantResponse struct {
	Response             *string  `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRestaurantResponse) Reset()         { *m = AddRestaurantResponse{} }
func (m *AddRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*AddRestaurantResponse) ProtoMessage()    {}
func (*AddRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{15}
}

func (m *AddRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRestaurantResponse.Unmarshal(m, b)
}
func (m *AddRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *AddRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRestaurantResponse.Merge(m, src)
}
func (m *AddRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_AddRestaurantResponse.Size(m)
}
func (m *AddRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRestaurantResponse proto.InternalMessageInfo

func (m *AddRestaurantResponse) GetResponse() string {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return ""
}

type AddMenuRequest struct {
	RestId               *string     `protobuf:"bytes,1,opt,name=restId" json:"restId,omitempty"`
	Item                 []*MenuItem `protobuf:"bytes,2,rep,name=item" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddMenuRequest) Reset()         { *m = AddMenuRequest{} }
func (m *AddMenuRequest) String() string { return proto.CompactTextString(m) }
func (*AddMenuRequest) ProtoMessage()    {}
func (*AddMenuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{16}
}

func (m *AddMenuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMenuRequest.Unmarshal(m, b)
}
func (m *AddMenuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMenuRequest.Marshal(b, m, deterministic)
}
func (m *AddMenuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMenuRequest.Merge(m, src)
}
func (m *AddMenuRequest) XXX_Size() int {
	return xxx_messageInfo_AddMenuRequest.Size(m)
}
func (m *AddMenuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMenuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMenuRequest proto.InternalMessageInfo

func (m *AddMenuRequest) GetRestId() string {
	if m != nil && m.RestId != nil {
		return *m.RestId
	}
	return ""
}

func (m *AddMenuRequest) GetItem() []*MenuItem {
	if m != nil {
		return m.Item
	}
	return nil
}

type AddMenuResponse struct {
	Response             *ResponseType `protobuf:"varint,1,opt,name=response,enum=ccgobbles_server.ResponseType" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddMenuResponse) Reset()         { *m = AddMenuResponse{} }
func (m *AddMenuResponse) String() string { return proto.CompactTextString(m) }
func (*AddMenuResponse) ProtoMessage()    {}
func (*AddMenuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{17}
}

func (m *AddMenuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMenuResponse.Unmarshal(m, b)
}
func (m *AddMenuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMenuResponse.Marshal(b, m, deterministic)
}
func (m *AddMenuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMenuResponse.Merge(m, src)
}
func (m *AddMenuResponse) XXX_Size() int {
	return xxx_messageInfo_AddMenuResponse.Size(m)
}
func (m *AddMenuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMenuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddMenuResponse proto.InternalMessageInfo

func (m *AddMenuResponse) GetResponse() ResponseType {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return ResponseType_SUCCESS
}

type CreateOrderRequest struct {
	Email                *string      `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	RestId               *string      `protobuf:"bytes,2,opt,name=restId" json:"restId,omitempty"`
	OrderId              *string      `protobuf:"bytes,3,opt,name=orderId" json:"orderId,omitempty"`
	OrderItem            []*OrderItem `protobuf:"bytes,4,rep,name=orderItem" json:"orderItem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{18}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *CreateOrderRequest) GetRestId() string {
	if m != nil && m.RestId != nil {
		return *m.RestId
	}
	return ""
}

func (m *CreateOrderRequest) GetOrderId() string {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return ""
}

func (m *CreateOrderRequest) GetOrderItem() []*OrderItem {
	if m != nil {
		return m.OrderItem
	}
	return nil
}

type CreateOrderResponse struct {
	Response             *string  `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78765c1dc4a8f6bd, []int{19}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetResponse() string {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return ""
}

func init() {
	proto.RegisterEnum("ccgobbles_server.ResponseType", ResponseType_name, ResponseType_value)
	proto.RegisterType((*Address)(nil), "ccgobbles_server.Address")
	proto.RegisterType((*User)(nil), "ccgobbles_server.User")
	proto.RegisterType((*MenuItem)(nil), "ccgobbles_server.MenuItem")
	proto.RegisterType((*Restaurant)(nil), "ccgobbles_server.Restaurant")
	proto.RegisterType((*Order)(nil), "ccgobbles_server.Order")
	proto.RegisterType((*OrderItem)(nil), "ccgobbles_server.OrderItem")
	proto.RegisterType((*RegisterUserRequest)(nil), "ccgobbles_server.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "ccgobbles_server.RegisterUserResponse")
	proto.RegisterType((*LoginUserRequest)(nil), "ccgobbles_server.LoginUserRequest")
	proto.RegisterType((*LoginUserResponse)(nil), "ccgobbles_server.LoginUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "ccgobbles_server.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "ccgobbles_server.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "ccgobbles_server.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "ccgobbles_server.DeleteUserResponse")
	proto.RegisterType((*AddRestaurantRequest)(nil), "ccgobbles_server.AddRestaurantRequest")
	proto.RegisterType((*AddRestaurantResponse)(nil), "ccgobbles_server.AddRestaurantResponse")
	proto.RegisterType((*AddMenuRequest)(nil), "ccgobbles_server.AddMenuRequest")
	proto.RegisterType((*AddMenuResponse)(nil), "ccgobbles_server.AddMenuResponse")
	proto.RegisterType((*CreateOrderRequest)(nil), "ccgobbles_server.CreateOrderRequest")
	proto.RegisterType((*CreateOrderResponse)(nil), "ccgobbles_server.CreateOrderResponse")
}

func init() {
	proto.RegisterFile("proto/ccgobbles_server/ccgobbles_server.proto", fileDescriptor_78765c1dc4a8f6bd)
}

var fileDescriptor_78765c1dc4a8f6bd = []byte{
	// 779 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xed, 0x6e, 0xd3, 0x4a,
	0x10, 0xad, 0x13, 0xa7, 0x49, 0x26, 0xbd, 0xbd, 0xe9, 0xb6, 0x37, 0xf2, 0xf5, 0xad, 0xae, 0xaa,
	0x85, 0x96, 0x52, 0x89, 0x16, 0x52, 0x40, 0x02, 0x21, 0xa1, 0x90, 0x16, 0x14, 0xa9, 0x2d, 0x92,
	0xdb, 0x20, 0xbe, 0xa4, 0xca, 0x89, 0x97, 0x62, 0x29, 0xb1, 0xd3, 0xdd, 0x0d, 0xa8, 0xfc, 0xe3,
	0x29, 0x78, 0x04, 0x9e, 0x01, 0x89, 0x87, 0x43, 0xbb, 0x5e, 0xdb, 0x9b, 0xd8, 0x6d, 0xf2, 0xcf,
	0x67, 0x72, 0x66, 0xe6, 0xcc, 0x78, 0x8e, 0x5b, 0xb8, 0x37, 0xa2, 0x21, 0x0f, 0xf7, 0xfa, 0xfd,
	0x8b, 0xb0, 0xd7, 0x1b, 0x10, 0x76, 0xce, 0x08, 0xfd, 0x42, 0x68, 0x26, 0xb0, 0x2b, 0x79, 0xa8,
	0x3e, 0x1d, 0xc7, 0xdf, 0x0d, 0x28, 0xb7, 0x3c, 0x8f, 0x12, 0xc6, 0x10, 0x86, 0x25, 0xc6, 0x29,
	0x21, 0xfc, 0x64, 0x3c, 0xec, 0x11, 0x6a, 0x19, 0x1b, 0xc6, 0x76, 0xd5, 0x99, 0x88, 0xa1, 0x06,
	0x2c, 0x46, 0xd8, 0x2a, 0xc8, 0x5f, 0x15, 0x42, 0x08, 0xcc, 0xbe, 0xcf, 0xaf, 0xac, 0xa2, 0x8c,
	0xca, 0x67, 0xb4, 0x06, 0x25, 0xc6, 0x5d, 0x4e, 0x2c, 0x53, 0x06, 0x23, 0x80, 0xea, 0x50, 0xfc,
	0xe6, 0x8f, 0xac, 0x92, 0x8c, 0x89, 0x47, 0xfc, 0xd3, 0x00, 0xb3, 0xcb, 0x08, 0x45, 0xeb, 0x50,
	0xfd, 0xe4, 0x53, 0xc6, 0x4f, 0xdc, 0x21, 0x51, 0xdd, 0xd3, 0x00, 0xb2, 0xa1, 0x32, 0x70, 0xd5,
	0x8f, 0x51, 0xf3, 0x04, 0x8b, 0x56, 0x64, 0xe8, 0xfa, 0x03, 0xd5, 0x3f, 0x02, 0x22, 0x63, 0xe4,
	0x32, 0xf6, 0x35, 0xa4, 0x9e, 0xd2, 0x90, 0x60, 0xb4, 0x0f, 0x65, 0x37, 0x9a, 0x5b, 0x4a, 0xa9,
	0x35, 0xff, 0xdd, 0xcd, 0x2c, 0x4d, 0x2d, 0xc6, 0x89, 0x99, 0xf8, 0x21, 0x54, 0x8e, 0x49, 0x30,
	0xee, 0x70, 0x32, 0x14, 0x13, 0x07, 0xa9, 0x4e, 0xf9, 0x2c, 0x64, 0x8c, 0xa8, 0xdf, 0x8f, 0xf4,
	0x19, 0x4e, 0x04, 0xf0, 0x2f, 0x03, 0xc0, 0x21, 0x8c, 0xbb, 0x63, 0xea, 0x06, 0x5c, 0x92, 0x3e,
	0x87, 0x41, 0x9c, 0x19, 0x81, 0x74, 0x82, 0x82, 0x3e, 0x41, 0xdc, 0xa4, 0xa8, 0x35, 0xd1, 0x94,
	0x9b, 0xf3, 0x2a, 0x47, 0x8f, 0xa1, 0x32, 0x24, 0xc1, 0xd8, 0xe7, 0x64, 0x68, 0x95, 0x36, 0x8a,
	0xdb, 0xb5, 0xa6, 0x9d, 0xcd, 0x8a, 0x67, 0x73, 0x12, 0x2e, 0x7e, 0x04, 0xa5, 0xd7, 0xd4, 0x23,
	0x34, 0xd5, 0x67, 0xe8, 0xfa, 0x1a, 0xb0, 0x48, 0x09, 0xe3, 0x1d, 0x2f, 0x3e, 0x87, 0x08, 0xe1,
	0xe7, 0x50, 0x95, 0x69, 0x72, 0x53, 0x0d, 0x58, 0x14, 0xf5, 0x3a, 0x9e, 0xca, 0x55, 0x48, 0xbc,
	0x9e, 0xcb, 0xb1, 0x1b, 0x70, 0x71, 0x37, 0x22, 0xbd, 0xe8, 0x24, 0x18, 0xb7, 0x60, 0xd5, 0x21,
	0x17, 0x3e, 0xe3, 0x84, 0x8a, 0xd3, 0x70, 0xc8, 0xe5, 0x98, 0x30, 0x8e, 0x76, 0xc0, 0x1c, 0x33,
	0x75, 0x9a, 0xb5, 0x66, 0x23, 0x3b, 0x82, 0x24, 0x4b, 0x0e, 0x6e, 0xc2, 0xda, 0x64, 0x09, 0x36,
	0x0a, 0x03, 0x26, 0xef, 0x88, 0xaa, 0x67, 0x25, 0x28, 0xc1, 0xf8, 0x00, 0xea, 0x47, 0xe1, 0x85,
	0x1f, 0xe8, 0x3d, 0xf3, 0x27, 0xd7, 0x6f, 0xab, 0x30, 0x79, 0x5b, 0x78, 0x0f, 0x56, 0xb4, 0x2a,
	0xd7, 0xb4, 0xad, 0x68, 0x6d, 0x3f, 0xc0, 0x4a, 0x77, 0xe4, 0xb9, 0x9c, 0xe8, 0x7d, 0x6d, 0xa8,
	0x84, 0x03, 0xef, 0x50, 0x6b, 0x9d, 0xe0, 0x64, 0x0f, 0x85, 0x39, 0xf6, 0x70, 0x1f, 0x90, 0x5e,
	0x7c, 0x8e, 0x2d, 0xdc, 0x85, 0x95, 0x03, 0x32, 0x20, 0x93, 0x72, 0x72, 0xd7, 0x20, 0x8a, 0xeb,
	0xd4, 0x39, 0x8a, 0x9f, 0xc1, 0x5a, 0xcb, 0xf3, 0x52, 0x3f, 0xc4, 0xf5, 0x9f, 0x01, 0xd0, 0x24,
	0xa8, 0x5e, 0xf0, 0x7a, 0x76, 0x30, 0x2d, 0x51, 0xe3, 0xe3, 0x7d, 0xf8, 0x67, 0xaa, 0xea, 0x1c,
	0x52, 0xde, 0xc2, 0x72, 0xcb, 0xf3, 0xc4, 0xd5, 0xc7, 0x22, 0xd2, 0x7b, 0x36, 0xf4, 0x7b, 0x46,
	0xbb, 0x60, 0x4a, 0xeb, 0x14, 0x66, 0x5a, 0x47, 0xf2, 0xf0, 0x31, 0xfc, 0x9d, 0x54, 0x56, 0x42,
	0x9e, 0x4e, 0x09, 0x59, 0x6e, 0xfe, 0x9f, 0x3b, 0x9d, 0x64, 0x9c, 0x5d, 0x8d, 0x88, 0x26, 0xf4,
	0x87, 0x01, 0xa8, 0x4d, 0x89, 0xcb, 0x89, 0x74, 0xd5, 0xcd, 0x97, 0x79, 0x8d, 0x27, 0x91, 0x05,
	0xe5, 0x50, 0x7a, 0xd2, 0x53, 0x9f, 0x93, 0x18, 0xa2, 0x27, 0x50, 0x0d, 0x63, 0xb7, 0x5a, 0xa6,
	0x1c, 0xf1, 0xbf, 0xac, 0xb6, 0xc4, 0xd0, 0x4e, 0xca, 0xc6, 0x0f, 0x60, 0x75, 0x42, 0xd8, 0xec,
	0xad, 0xef, 0x6c, 0xc3, 0x92, 0x3e, 0x26, 0xaa, 0x41, 0xf9, 0xb4, 0xdb, 0x6e, 0x1f, 0x9e, 0x9e,
	0xd6, 0x17, 0x04, 0x78, 0xd9, 0xea, 0x1c, 0x75, 0x9d, 0xc3, 0xba, 0xd1, 0xfc, 0x6d, 0x42, 0xb5,
	0xdd, 0x7e, 0x15, 0xc9, 0x40, 0xe7, 0x22, 0x2f, 0xf5, 0x33, 0xda, 0xcc, 0x5b, 0x5f, 0xe6, 0x93,
	0x61, 0x6f, 0xcd, 0xa2, 0xa9, 0x1d, 0x2f, 0xa0, 0x37, 0x50, 0x4d, 0x6c, 0x8b, 0x70, 0x36, 0x6d,
	0xfa, 0xcb, 0x60, 0xdf, 0xba, 0x91, 0x93, 0xd4, 0x7d, 0x07, 0x90, 0x1a, 0x10, 0xe5, 0x24, 0x65,
	0xbc, 0x6f, 0xdf, 0xbe, 0x99, 0xa4, 0x97, 0x4e, 0xed, 0x97, 0x57, 0x3a, 0xe3, 0xe3, 0xbc, 0xd2,
	0x59, 0x07, 0xe3, 0x05, 0xd4, 0x83, 0xbf, 0x26, 0x1c, 0x85, 0xb6, 0x72, 0xff, 0xcc, 0x64, 0x8c,
	0x6c, 0xdf, 0x99, 0xc9, 0x4b, 0x7a, 0x7c, 0x84, 0x9a, 0x76, 0x3d, 0x28, 0x47, 0x5a, 0xf6, 0xea,
	0xed, 0xcd, 0x19, 0xac, 0xb8, 0xfa, 0x0b, 0xeb, 0x7d, 0x23, 0xff, 0xdf, 0xa3, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x58, 0x21, 0x09, 0xbf, 0x37, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CCGobblesClient is the client API for CCGobbles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CCGobblesClient interface {
	// Unary API to register user
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	// // Unary API to login user
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	// // Unary API to update user
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	// // Unary API to delete user
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	// // Unary API to add restaurant
	AddRestaurant(ctx context.Context, in *AddRestaurantRequest, opts ...grpc.CallOption) (*AddRestaurantResponse, error)
	// // Unary API to create orders
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
}

type cCGobblesClient struct {
	cc *grpc.ClientConn
}

func NewCCGobblesClient(cc *grpc.ClientConn) CCGobblesClient {
	return &cCGobblesClient{cc}
}

func (c *cCGobblesClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, "/ccgobbles_server.CCGobbles/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cCGobblesClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/ccgobbles_server.CCGobbles/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cCGobblesClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/ccgobbles_server.CCGobbles/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cCGobblesClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/ccgobbles_server.CCGobbles/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cCGobblesClient) AddRestaurant(ctx context.Context, in *AddRestaurantRequest, opts ...grpc.CallOption) (*AddRestaurantResponse, error) {
	out := new(AddRestaurantResponse)
	err := c.cc.Invoke(ctx, "/ccgobbles_server.CCGobbles/AddRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cCGobblesClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/ccgobbles_server.CCGobbles/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CCGobblesServer is the server API for CCGobbles service.
type CCGobblesServer interface {
	// Unary API to register user
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	// // Unary API to login user
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	// // Unary API to update user
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	// // Unary API to delete user
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	// // Unary API to add restaurant
	AddRestaurant(context.Context, *AddRestaurantRequest) (*AddRestaurantResponse, error)
	// // Unary API to create orders
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
}

// UnimplementedCCGobblesServer can be embedded to have forward compatible implementations.
type UnimplementedCCGobblesServer struct {
}

func (*UnimplementedCCGobblesServer) RegisterUser(ctx context.Context, req *RegisterUserRequest) (*RegisterUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (*UnimplementedCCGobblesServer) LoginUser(ctx context.Context, req *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (*UnimplementedCCGobblesServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedCCGobblesServer) DeleteUser(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedCCGobblesServer) AddRestaurant(ctx context.Context, req *AddRestaurantRequest) (*AddRestaurantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRestaurant not implemented")
}
func (*UnimplementedCCGobblesServer) CreateOrder(ctx context.Context, req *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}

func RegisterCCGobblesServer(s *grpc.Server, srv CCGobblesServer) {
	s.RegisterService(&_CCGobbles_serviceDesc, srv)
}

func _CCGobbles_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CCGobblesServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ccgobbles_server.CCGobbles/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CCGobblesServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CCGobbles_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CCGobblesServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ccgobbles_server.CCGobbles/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CCGobblesServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CCGobbles_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CCGobblesServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ccgobbles_server.CCGobbles/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CCGobblesServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CCGobbles_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CCGobblesServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ccgobbles_server.CCGobbles/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CCGobblesServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CCGobbles_AddRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CCGobblesServer).AddRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ccgobbles_server.CCGobbles/AddRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CCGobblesServer).AddRestaurant(ctx, req.(*AddRestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CCGobbles_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CCGobblesServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ccgobbles_server.CCGobbles/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CCGobblesServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CCGobbles_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ccgobbles_server.CCGobbles",
	HandlerType: (*CCGobblesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _CCGobbles_RegisterUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _CCGobbles_LoginUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _CCGobbles_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _CCGobbles_DeleteUser_Handler,
		},
		{
			MethodName: "AddRestaurant",
			Handler:    _CCGobbles_AddRestaurant_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _CCGobbles_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ccgobbles_server/ccgobbles_server.proto",
}
