// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/restaurant_server/restaurant_server.proto

package restaurant_server

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Restaurant struct {
	Phone                string      `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string      `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address              *Address    `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Menuitem             []*MenuItem `protobuf:"bytes,5,rep,name=menuitem,proto3" json:"menuitem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Restaurant) Reset()         { *m = Restaurant{} }
func (m *Restaurant) String() string { return proto.CompactTextString(m) }
func (*Restaurant) ProtoMessage()    {}
func (*Restaurant) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b6e153559ae89a4, []int{0}
}

func (m *Restaurant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restaurant.Unmarshal(m, b)
}
func (m *Restaurant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restaurant.Marshal(b, m, deterministic)
}
func (m *Restaurant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restaurant.Merge(m, src)
}
func (m *Restaurant) XXX_Size() int {
	return xxx_messageInfo_Restaurant.Size(m)
}
func (m *Restaurant) XXX_DiscardUnknown() {
	xxx_messageInfo_Restaurant.DiscardUnknown(m)
}

var xxx_messageInfo_Restaurant proto.InternalMessageInfo

func (m *Restaurant) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Restaurant) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Restaurant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Restaurant) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Restaurant) GetMenuitem() []*MenuItem {
	if m != nil {
		return m.Menuitem
	}
	return nil
}

type Address struct {
	StreetNumber         string   `protobuf:"bytes,1,opt,name=streetNumber,proto3" json:"streetNumber,omitempty"`
	Street               string   `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Zip                  string   `protobuf:"bytes,5,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b6e153559ae89a4, []int{1}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetStreetNumber() string {
	if m != nil {
		return m.StreetNumber
	}
	return ""
}

func (m *Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

type MenuItem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price                float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenuItem) Reset()         { *m = MenuItem{} }
func (m *MenuItem) String() string { return proto.CompactTextString(m) }
func (*MenuItem) ProtoMessage()    {}
func (*MenuItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b6e153559ae89a4, []int{2}
}

func (m *MenuItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuItem.Unmarshal(m, b)
}
func (m *MenuItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuItem.Marshal(b, m, deterministic)
}
func (m *MenuItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuItem.Merge(m, src)
}
func (m *MenuItem) XXX_Size() int {
	return xxx_messageInfo_MenuItem.Size(m)
}
func (m *MenuItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuItem.DiscardUnknown(m)
}

var xxx_messageInfo_MenuItem proto.InternalMessageInfo

func (m *MenuItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MenuItem) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type AddRestaurantRequest struct {
	Restaurant           *Restaurant `protobuf:"bytes,1,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddRestaurantRequest) Reset()         { *m = AddRestaurantRequest{} }
func (m *AddRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*AddRestaurantRequest) ProtoMessage()    {}
func (*AddRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b6e153559ae89a4, []int{3}
}

func (m *AddRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRestaurantRequest.Unmarshal(m, b)
}
func (m *AddRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *AddRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRestaurantRequest.Merge(m, src)
}
func (m *AddRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_AddRestaurantRequest.Size(m)
}
func (m *AddRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRestaurantRequest proto.InternalMessageInfo

func (m *AddRestaurantRequest) GetRestaurant() *Restaurant {
	if m != nil {
		return m.Restaurant
	}
	return nil
}

type AddRestaurantResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRestaurantResponse) Reset()         { *m = AddRestaurantResponse{} }
func (m *AddRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*AddRestaurantResponse) ProtoMessage()    {}
func (*AddRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b6e153559ae89a4, []int{4}
}

func (m *AddRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRestaurantResponse.Unmarshal(m, b)
}
func (m *AddRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *AddRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRestaurantResponse.Merge(m, src)
}
func (m *AddRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_AddRestaurantResponse.Size(m)
}
func (m *AddRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRestaurantResponse proto.InternalMessageInfo

func (m *AddRestaurantResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type UpdateRestaurantRequest struct {
	OldEmail             string      `protobuf:"bytes,1,opt,name=oldEmail,proto3" json:"oldEmail,omitempty"`
	OldPhone             string      `protobuf:"bytes,2,opt,name=oldPhone,proto3" json:"oldPhone,omitempty"`
	Restaurant           *Restaurant `protobuf:"bytes,3,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateRestaurantRequest) Reset()         { *m = UpdateRestaurantRequest{} }
func (m *UpdateRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRestaurantRequest) ProtoMessage()    {}
func (*UpdateRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b6e153559ae89a4, []int{5}
}

func (m *UpdateRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRestaurantRequest.Unmarshal(m, b)
}
func (m *UpdateRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRestaurantRequest.Merge(m, src)
}
func (m *UpdateRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRestaurantRequest.Size(m)
}
func (m *UpdateRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRestaurantRequest proto.InternalMessageInfo

func (m *UpdateRestaurantRequest) GetOldEmail() string {
	if m != nil {
		return m.OldEmail
	}
	return ""
}

func (m *UpdateRestaurantRequest) GetOldPhone() string {
	if m != nil {
		return m.OldPhone
	}
	return ""
}

func (m *UpdateRestaurantRequest) GetRestaurant() *Restaurant {
	if m != nil {
		return m.Restaurant
	}
	return nil
}

type UpdateRestaurantResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRestaurantResponse) Reset()         { *m = UpdateRestaurantResponse{} }
func (m *UpdateRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRestaurantResponse) ProtoMessage()    {}
func (*UpdateRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b6e153559ae89a4, []int{6}
}

func (m *UpdateRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRestaurantResponse.Unmarshal(m, b)
}
func (m *UpdateRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRestaurantResponse.Merge(m, src)
}
func (m *UpdateRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRestaurantResponse.Size(m)
}
func (m *UpdateRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRestaurantResponse proto.InternalMessageInfo

func (m *UpdateRestaurantResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type DeleteRestaurantRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRestaurantRequest) Reset()         { *m = DeleteRestaurantRequest{} }
func (m *DeleteRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRestaurantRequest) ProtoMessage()    {}
func (*DeleteRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b6e153559ae89a4, []int{7}
}

func (m *DeleteRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRestaurantRequest.Unmarshal(m, b)
}
func (m *DeleteRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRestaurantRequest.Merge(m, src)
}
func (m *DeleteRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRestaurantRequest.Size(m)
}
func (m *DeleteRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRestaurantRequest proto.InternalMessageInfo

func (m *DeleteRestaurantRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *DeleteRestaurantRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type DeleteRestaurantResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRestaurantResponse) Reset()         { *m = DeleteRestaurantResponse{} }
func (m *DeleteRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRestaurantResponse) ProtoMessage()    {}
func (*DeleteRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b6e153559ae89a4, []int{8}
}

func (m *DeleteRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRestaurantResponse.Unmarshal(m, b)
}
func (m *DeleteRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRestaurantResponse.Merge(m, src)
}
func (m *DeleteRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRestaurantResponse.Size(m)
}
func (m *DeleteRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRestaurantResponse proto.InternalMessageInfo

func (m *DeleteRestaurantResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*Restaurant)(nil), "restaurant_server.Restaurant")
	proto.RegisterType((*Address)(nil), "restaurant_server.Address")
	proto.RegisterType((*MenuItem)(nil), "restaurant_server.MenuItem")
	proto.RegisterType((*AddRestaurantRequest)(nil), "restaurant_server.AddRestaurantRequest")
	proto.RegisterType((*AddRestaurantResponse)(nil), "restaurant_server.AddRestaurantResponse")
	proto.RegisterType((*UpdateRestaurantRequest)(nil), "restaurant_server.UpdateRestaurantRequest")
	proto.RegisterType((*UpdateRestaurantResponse)(nil), "restaurant_server.UpdateRestaurantResponse")
	proto.RegisterType((*DeleteRestaurantRequest)(nil), "restaurant_server.DeleteRestaurantRequest")
	proto.RegisterType((*DeleteRestaurantResponse)(nil), "restaurant_server.DeleteRestaurantResponse")
}

func init() {
	proto.RegisterFile("proto/restaurant_server/restaurant_server.proto", fileDescriptor_9b6e153559ae89a4)
}

var fileDescriptor_9b6e153559ae89a4 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x8b, 0xd3, 0x40,
	0x18, 0xde, 0x49, 0xb6, 0xbb, 0xd9, 0x37, 0x0a, 0xeb, 0xb0, 0xda, 0x18, 0x11, 0xca, 0x5c, 0x0c,
	0x0a, 0xbb, 0x90, 0x16, 0x3d, 0x79, 0xa8, 0xd8, 0x83, 0x07, 0x45, 0x02, 0xbd, 0x78, 0x91, 0xb4,
	0x79, 0xc1, 0x40, 0xf3, 0xe1, 0xcc, 0x44, 0xd0, 0x9b, 0xff, 0xc0, 0xff, 0xe3, 0xaf, 0xf0, 0x1f,
	0x49, 0x26, 0x93, 0x34, 0xcd, 0x07, 0xed, 0xde, 0xe6, 0x79, 0xbf, 0x9f, 0xe7, 0x7d, 0x13, 0xb8,
	0xcb, 0x79, 0x26, 0xb3, 0x3b, 0x8e, 0x42, 0x86, 0x05, 0x0f, 0x53, 0xf9, 0x55, 0x20, 0xff, 0x81,
	0xbc, 0x6f, 0xb9, 0x55, 0x91, 0xf4, 0x51, 0xcf, 0xc1, 0xfe, 0x12, 0x80, 0xa0, 0xb1, 0xd2, 0x1b,
	0x98, 0xe4, 0xdf, 0xb2, 0x14, 0x1d, 0x32, 0x23, 0xde, 0x55, 0x50, 0x81, 0xd2, 0x8a, 0x49, 0x18,
	0xef, 0x1c, 0xa3, 0xb2, 0x2a, 0x40, 0x29, 0x9c, 0xa7, 0x61, 0x82, 0x8e, 0xa9, 0x8c, 0xea, 0x4d,
	0x17, 0x70, 0x19, 0x46, 0x11, 0x47, 0x21, 0x9c, 0xf3, 0x19, 0xf1, 0x6c, 0xdf, 0xbd, 0xed, 0x0f,
	0xb3, 0xac, 0x22, 0x82, 0x3a, 0x94, 0xbe, 0x01, 0x2b, 0xc1, 0xb4, 0x88, 0x25, 0x26, 0xce, 0x64,
	0x66, 0x7a, 0xb6, 0xff, 0x6c, 0x20, 0xed, 0x23, 0xa6, 0xc5, 0x07, 0x89, 0x49, 0xd0, 0x04, 0xb3,
	0xdf, 0x04, 0x2e, 0x75, 0x35, 0xca, 0xe0, 0x81, 0x90, 0x1c, 0x51, 0x7e, 0x2a, 0x92, 0x0d, 0x72,
	0xcd, 0xe0, 0xc0, 0x46, 0x9f, 0xc0, 0x45, 0x85, 0x35, 0x13, 0x8d, 0x4a, 0x2a, 0xdb, 0x58, 0xfe,
	0xac, 0xa9, 0x94, 0xef, 0x92, 0xb4, 0x90, 0xa1, 0x44, 0x45, 0xe4, 0x2a, 0xa8, 0x00, 0xbd, 0x06,
	0xf3, 0x57, 0x9c, 0x3b, 0x13, 0x65, 0x2b, 0x9f, 0x6c, 0x01, 0x56, 0x3d, 0x59, 0x23, 0x09, 0x69,
	0x49, 0x52, 0x4a, 0xca, 0xe3, 0x2d, 0xaa, 0x96, 0x24, 0xa8, 0x00, 0x5b, 0xc3, 0xcd, 0x32, 0x8a,
	0xf6, 0xca, 0x07, 0xf8, 0xbd, 0x40, 0x21, 0xe9, 0x5b, 0x80, 0x3d, 0x73, 0x55, 0xc7, 0xf6, 0x9f,
	0x0f, 0x88, 0xd1, 0xca, 0x6c, 0x25, 0xb0, 0x39, 0x3c, 0xee, 0x94, 0x15, 0x79, 0x96, 0x0a, 0xa4,
	0x2e, 0x58, 0x5c, 0xbf, 0xf5, 0x74, 0x0d, 0x66, 0x7f, 0x08, 0x4c, 0xd7, 0x79, 0x14, 0x4a, 0xec,
	0xcf, 0xe3, 0x82, 0x95, 0xed, 0xa2, 0x95, 0xda, 0xbe, 0xce, 0xab, 0xb1, 0xf6, 0x7d, 0x56, 0xf7,
	0x62, 0x34, 0x3e, 0x85, 0x3b, 0x3c, 0xcc, 0xfb, 0xf2, 0x78, 0x0d, 0x4e, 0x7f, 0xa2, 0x13, 0xa8,
	0xac, 0x60, 0xfa, 0x1e, 0x77, 0x38, 0xc4, 0xa4, 0x39, 0x62, 0xd2, 0x3e, 0xe2, 0xe6, 0xe0, 0x8d,
	0xd6, 0xc1, 0x97, 0xed, 0xfb, 0x65, 0x8e, 0xb7, 0xf7, 0xff, 0x19, 0x60, 0xef, 0x53, 0x04, 0x8d,
	0xe0, 0xe1, 0xc1, 0x3a, 0xe8, 0x8b, 0xe1, 0xcf, 0xa1, 0x37, 0xad, 0xeb, 0x1d, 0x0f, 0xd4, 0x94,
	0xcf, 0x68, 0x02, 0xd7, 0x5d, 0xb1, 0xe8, 0xcb, 0x81, 0xfc, 0x91, 0x1d, 0xbb, 0xaf, 0x4e, 0x8a,
	0x6d, 0xb7, 0xeb, 0x8a, 0x33, 0xd8, 0x6e, 0x64, 0x11, 0x83, 0xed, 0xc6, 0xd4, 0x66, 0x67, 0xef,
	0x9e, 0x7e, 0x99, 0x8e, 0xfc, 0xe7, 0x36, 0x17, 0xca, 0x31, 0xff, 0x1f, 0x00, 0x00, 0xff, 0xff,
	0xd0, 0x9d, 0x27, 0xed, 0x09, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RestaurantsClient is the client API for Restaurants service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RestaurantsClient interface {
	// Unary API to add restaurant
	AddRestaurant(ctx context.Context, in *AddRestaurantRequest, opts ...grpc.CallOption) (*AddRestaurantResponse, error)
	// Unary API to update restaurant info
	UpdateRestaurant(ctx context.Context, in *UpdateRestaurantRequest, opts ...grpc.CallOption) (*UpdateRestaurantResponse, error)
	// Unary API to delete restaurant
	DeleteRestaurant(ctx context.Context, in *DeleteRestaurantRequest, opts ...grpc.CallOption) (*DeleteRestaurantResponse, error)
}

type restaurantsClient struct {
	cc *grpc.ClientConn
}

func NewRestaurantsClient(cc *grpc.ClientConn) RestaurantsClient {
	return &restaurantsClient{cc}
}

func (c *restaurantsClient) AddRestaurant(ctx context.Context, in *AddRestaurantRequest, opts ...grpc.CallOption) (*AddRestaurantResponse, error) {
	out := new(AddRestaurantResponse)
	err := c.cc.Invoke(ctx, "/restaurant_server.Restaurants/AddRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantsClient) UpdateRestaurant(ctx context.Context, in *UpdateRestaurantRequest, opts ...grpc.CallOption) (*UpdateRestaurantResponse, error) {
	out := new(UpdateRestaurantResponse)
	err := c.cc.Invoke(ctx, "/restaurant_server.Restaurants/UpdateRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantsClient) DeleteRestaurant(ctx context.Context, in *DeleteRestaurantRequest, opts ...grpc.CallOption) (*DeleteRestaurantResponse, error) {
	out := new(DeleteRestaurantResponse)
	err := c.cc.Invoke(ctx, "/restaurant_server.Restaurants/DeleteRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurantsServer is the server API for Restaurants service.
type RestaurantsServer interface {
	// Unary API to add restaurant
	AddRestaurant(context.Context, *AddRestaurantRequest) (*AddRestaurantResponse, error)
	// Unary API to update restaurant info
	UpdateRestaurant(context.Context, *UpdateRestaurantRequest) (*UpdateRestaurantResponse, error)
	// Unary API to delete restaurant
	DeleteRestaurant(context.Context, *DeleteRestaurantRequest) (*DeleteRestaurantResponse, error)
}

// UnimplementedRestaurantsServer can be embedded to have forward compatible implementations.
type UnimplementedRestaurantsServer struct {
}

func (*UnimplementedRestaurantsServer) AddRestaurant(ctx context.Context, req *AddRestaurantRequest) (*AddRestaurantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRestaurant not implemented")
}
func (*UnimplementedRestaurantsServer) UpdateRestaurant(ctx context.Context, req *UpdateRestaurantRequest) (*UpdateRestaurantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRestaurant not implemented")
}
func (*UnimplementedRestaurantsServer) DeleteRestaurant(ctx context.Context, req *DeleteRestaurantRequest) (*DeleteRestaurantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRestaurant not implemented")
}

func RegisterRestaurantsServer(s *grpc.Server, srv RestaurantsServer) {
	s.RegisterService(&_Restaurants_serviceDesc, srv)
}

func _Restaurants_AddRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantsServer).AddRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurant_server.Restaurants/AddRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantsServer).AddRestaurant(ctx, req.(*AddRestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Restaurants_UpdateRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantsServer).UpdateRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurant_server.Restaurants/UpdateRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantsServer).UpdateRestaurant(ctx, req.(*UpdateRestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Restaurants_DeleteRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantsServer).DeleteRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurant_server.Restaurants/DeleteRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantsServer).DeleteRestaurant(ctx, req.(*DeleteRestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Restaurants_serviceDesc = grpc.ServiceDesc{
	ServiceName: "restaurant_server.Restaurants",
	HandlerType: (*RestaurantsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRestaurant",
			Handler:    _Restaurants_AddRestaurant_Handler,
		},
		{
			MethodName: "UpdateRestaurant",
			Handler:    _Restaurants_UpdateRestaurant_Handler,
		},
		{
			MethodName: "DeleteRestaurant",
			Handler:    _Restaurants_DeleteRestaurant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/restaurant_server/restaurant_server.proto",
}
