// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/restaurant_server/restaurant_server.proto

package restaurant_server

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Restaurant struct {
	Phone                string      `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string      `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address              *Address    `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Menuitem             []*MenuItem `protobuf:"bytes,5,rep,name=menuitem,proto3" json:"menuitem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Restaurant) Reset()         { *m = Restaurant{} }
func (m *Restaurant) String() string { return proto.CompactTextString(m) }
func (*Restaurant) ProtoMessage()    {}
func (*Restaurant) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b6e153559ae89a4, []int{0}
}

func (m *Restaurant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restaurant.Unmarshal(m, b)
}
func (m *Restaurant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restaurant.Marshal(b, m, deterministic)
}
func (m *Restaurant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restaurant.Merge(m, src)
}
func (m *Restaurant) XXX_Size() int {
	return xxx_messageInfo_Restaurant.Size(m)
}
func (m *Restaurant) XXX_DiscardUnknown() {
	xxx_messageInfo_Restaurant.DiscardUnknown(m)
}

var xxx_messageInfo_Restaurant proto.InternalMessageInfo

func (m *Restaurant) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Restaurant) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Restaurant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Restaurant) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Restaurant) GetMenuitem() []*MenuItem {
	if m != nil {
		return m.Menuitem
	}
	return nil
}

type Address struct {
	StreetNumber         string   `protobuf:"bytes,1,opt,name=streetNumber,proto3" json:"streetNumber,omitempty"`
	Street               string   `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Zip                  string   `protobuf:"bytes,5,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b6e153559ae89a4, []int{1}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetStreetNumber() string {
	if m != nil {
		return m.StreetNumber
	}
	return ""
}

func (m *Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

type MenuItem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price                float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenuItem) Reset()         { *m = MenuItem{} }
func (m *MenuItem) String() string { return proto.CompactTextString(m) }
func (*MenuItem) ProtoMessage()    {}
func (*MenuItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b6e153559ae89a4, []int{2}
}

func (m *MenuItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuItem.Unmarshal(m, b)
}
func (m *MenuItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuItem.Marshal(b, m, deterministic)
}
func (m *MenuItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuItem.Merge(m, src)
}
func (m *MenuItem) XXX_Size() int {
	return xxx_messageInfo_MenuItem.Size(m)
}
func (m *MenuItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuItem.DiscardUnknown(m)
}

var xxx_messageInfo_MenuItem proto.InternalMessageInfo

func (m *MenuItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MenuItem) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type AddRestaurantRequest struct {
	Restaurant           *Restaurant `protobuf:"bytes,1,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddRestaurantRequest) Reset()         { *m = AddRestaurantRequest{} }
func (m *AddRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*AddRestaurantRequest) ProtoMessage()    {}
func (*AddRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b6e153559ae89a4, []int{3}
}

func (m *AddRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRestaurantRequest.Unmarshal(m, b)
}
func (m *AddRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *AddRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRestaurantRequest.Merge(m, src)
}
func (m *AddRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_AddRestaurantRequest.Size(m)
}
func (m *AddRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRestaurantRequest proto.InternalMessageInfo

func (m *AddRestaurantRequest) GetRestaurant() *Restaurant {
	if m != nil {
		return m.Restaurant
	}
	return nil
}

type AddRestaurantResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRestaurantResponse) Reset()         { *m = AddRestaurantResponse{} }
func (m *AddRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*AddRestaurantResponse) ProtoMessage()    {}
func (*AddRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b6e153559ae89a4, []int{4}
}

func (m *AddRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRestaurantResponse.Unmarshal(m, b)
}
func (m *AddRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *AddRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRestaurantResponse.Merge(m, src)
}
func (m *AddRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_AddRestaurantResponse.Size(m)
}
func (m *AddRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRestaurantResponse proto.InternalMessageInfo

func (m *AddRestaurantResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type AddMenuRequest struct {
	RestId               string      `protobuf:"bytes,1,opt,name=restId,proto3" json:"restId,omitempty"`
	Item                 []*MenuItem `protobuf:"bytes,2,rep,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddMenuRequest) Reset()         { *m = AddMenuRequest{} }
func (m *AddMenuRequest) String() string { return proto.CompactTextString(m) }
func (*AddMenuRequest) ProtoMessage()    {}
func (*AddMenuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b6e153559ae89a4, []int{5}
}

func (m *AddMenuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMenuRequest.Unmarshal(m, b)
}
func (m *AddMenuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMenuRequest.Marshal(b, m, deterministic)
}
func (m *AddMenuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMenuRequest.Merge(m, src)
}
func (m *AddMenuRequest) XXX_Size() int {
	return xxx_messageInfo_AddMenuRequest.Size(m)
}
func (m *AddMenuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMenuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMenuRequest proto.InternalMessageInfo

func (m *AddMenuRequest) GetRestId() string {
	if m != nil {
		return m.RestId
	}
	return ""
}

func (m *AddMenuRequest) GetItem() []*MenuItem {
	if m != nil {
		return m.Item
	}
	return nil
}

type AddMenuResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMenuResponse) Reset()         { *m = AddMenuResponse{} }
func (m *AddMenuResponse) String() string { return proto.CompactTextString(m) }
func (*AddMenuResponse) ProtoMessage()    {}
func (*AddMenuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b6e153559ae89a4, []int{6}
}

func (m *AddMenuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMenuResponse.Unmarshal(m, b)
}
func (m *AddMenuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMenuResponse.Marshal(b, m, deterministic)
}
func (m *AddMenuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMenuResponse.Merge(m, src)
}
func (m *AddMenuResponse) XXX_Size() int {
	return xxx_messageInfo_AddMenuResponse.Size(m)
}
func (m *AddMenuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMenuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddMenuResponse proto.InternalMessageInfo

func (m *AddMenuResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*Restaurant)(nil), "restaurant_server.Restaurant")
	proto.RegisterType((*Address)(nil), "restaurant_server.Address")
	proto.RegisterType((*MenuItem)(nil), "restaurant_server.MenuItem")
	proto.RegisterType((*AddRestaurantRequest)(nil), "restaurant_server.AddRestaurantRequest")
	proto.RegisterType((*AddRestaurantResponse)(nil), "restaurant_server.AddRestaurantResponse")
	proto.RegisterType((*AddMenuRequest)(nil), "restaurant_server.AddMenuRequest")
	proto.RegisterType((*AddMenuResponse)(nil), "restaurant_server.AddMenuResponse")
}

func init() {
	proto.RegisterFile("proto/restaurant_server/restaurant_server.proto", fileDescriptor_9b6e153559ae89a4)
}

var fileDescriptor_9b6e153559ae89a4 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x3d, 0x4f, 0xc3, 0x30,
	0x14, 0x24, 0xfd, 0xee, 0x0b, 0x9f, 0x56, 0x29, 0xa1, 0x08, 0xa9, 0xf2, 0x42, 0x16, 0x5a, 0x29,
	0xad, 0xc4, 0xc4, 0x50, 0xb6, 0x0e, 0x30, 0x44, 0x62, 0x80, 0x05, 0xa5, 0xf5, 0x93, 0x88, 0x44,
	0x3e, 0xb0, 0x1d, 0x24, 0xd8, 0xf8, 0x5d, 0xfc, 0x39, 0x64, 0xc7, 0x49, 0x5b, 0x52, 0xd4, 0xed,
	0xdd, 0xf9, 0xfc, 0x7a, 0x77, 0x6e, 0x60, 0x9c, 0xf2, 0x44, 0x26, 0x63, 0x8e, 0x42, 0x06, 0x19,
	0x0f, 0x62, 0xf9, 0x22, 0x90, 0x7f, 0x20, 0xaf, 0x32, 0x23, 0xad, 0x24, 0x27, 0x95, 0x03, 0xfa,
	0x63, 0x01, 0xf8, 0x25, 0x4b, 0x7a, 0xd0, 0x4c, 0x5f, 0x93, 0x18, 0x1d, 0x6b, 0x68, 0xb9, 0x5d,
	0x3f, 0x07, 0x8a, 0xc5, 0x28, 0x08, 0xdf, 0x9c, 0x5a, 0xce, 0x6a, 0x40, 0x08, 0x34, 0xe2, 0x20,
	0x42, 0xa7, 0xae, 0x49, 0x3d, 0x93, 0x29, 0xb4, 0x03, 0xc6, 0x38, 0x0a, 0xe1, 0x34, 0x86, 0x96,
	0x6b, 0x7b, 0x83, 0x51, 0xd5, 0xcc, 0x2c, 0x57, 0xf8, 0x85, 0x94, 0xdc, 0x40, 0x27, 0xc2, 0x38,
	0x0b, 0x25, 0x46, 0x4e, 0x73, 0x58, 0x77, 0x6d, 0xef, 0x62, 0xcb, 0xb5, 0x7b, 0x8c, 0xb3, 0xb9,
	0xc4, 0xc8, 0x2f, 0xc5, 0xf4, 0xdb, 0x82, 0xb6, 0xd9, 0x46, 0x28, 0xec, 0x0b, 0xc9, 0x11, 0xe5,
	0x43, 0x16, 0x2d, 0x90, 0x9b, 0x04, 0x1b, 0x1c, 0xe9, 0x43, 0x2b, 0xc7, 0x26, 0x89, 0x41, 0x2a,
	0xca, 0x32, 0x94, 0x9f, 0x45, 0x14, 0x35, 0xab, 0xd0, 0x42, 0x06, 0x12, 0x75, 0x90, 0xae, 0x9f,
	0x03, 0x72, 0x0c, 0xf5, 0xaf, 0x30, 0x75, 0x9a, 0x9a, 0x53, 0x23, 0x9d, 0x42, 0xa7, 0x70, 0x56,
	0x56, 0x62, 0xad, 0x55, 0xa2, 0x2a, 0xe5, 0xe1, 0x12, 0xf5, 0x4f, 0x5a, 0x7e, 0x0e, 0xe8, 0x23,
	0xf4, 0x66, 0x8c, 0xad, 0x9a, 0xf7, 0xf1, 0x3d, 0x43, 0x21, 0xc9, 0x2d, 0xc0, 0x2a, 0xb9, 0xde,
	0x63, 0x7b, 0x97, 0x5b, 0xca, 0x58, 0xbb, 0xb9, 0x76, 0x81, 0x4e, 0xe0, 0xf4, 0xcf, 0x5a, 0x91,
	0x26, 0xb1, 0x40, 0x32, 0x80, 0x0e, 0x37, 0xb3, 0x71, 0x57, 0x62, 0xfa, 0x04, 0x87, 0x33, 0xc6,
	0x54, 0x88, 0xc2, 0x45, 0x1f, 0x5a, 0x6a, 0xe9, 0x9c, 0x19, 0xad, 0x41, 0x64, 0x0c, 0x0d, 0xfd,
	0x48, 0xb5, 0xdd, 0x8f, 0xa4, 0x85, 0xf4, 0x1a, 0x8e, 0xca, 0xd5, 0xbb, 0x9d, 0x78, 0x02, 0xec,
	0x95, 0x77, 0x41, 0x18, 0x1c, 0x6c, 0xa4, 0x21, 0x57, 0xdb, 0xff, 0x4d, 0x95, 0x1a, 0x07, 0xee,
	0x6e, 0xa1, 0x09, 0xbf, 0x77, 0x77, 0xfe, 0x7c, 0xf6, 0xcf, 0x87, 0xb4, 0x68, 0xe9, 0x83, 0xc9,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xf8, 0x35, 0x42, 0x6a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RestaurantsClient is the client API for Restaurants service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RestaurantsClient interface {
	// // Unary API to add restaurant
	AddRestaurant(ctx context.Context, in *AddRestaurantRequest, opts ...grpc.CallOption) (*AddRestaurantResponse, error)
}

type restaurantsClient struct {
	cc *grpc.ClientConn
}

func NewRestaurantsClient(cc *grpc.ClientConn) RestaurantsClient {
	return &restaurantsClient{cc}
}

func (c *restaurantsClient) AddRestaurant(ctx context.Context, in *AddRestaurantRequest, opts ...grpc.CallOption) (*AddRestaurantResponse, error) {
	out := new(AddRestaurantResponse)
	err := c.cc.Invoke(ctx, "/restaurant_server.Restaurants/AddRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurantsServer is the server API for Restaurants service.
type RestaurantsServer interface {
	// // Unary API to add restaurant
	AddRestaurant(context.Context, *AddRestaurantRequest) (*AddRestaurantResponse, error)
}

// UnimplementedRestaurantsServer can be embedded to have forward compatible implementations.
type UnimplementedRestaurantsServer struct {
}

func (*UnimplementedRestaurantsServer) AddRestaurant(ctx context.Context, req *AddRestaurantRequest) (*AddRestaurantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRestaurant not implemented")
}

func RegisterRestaurantsServer(s *grpc.Server, srv RestaurantsServer) {
	s.RegisterService(&_Restaurants_serviceDesc, srv)
}

func _Restaurants_AddRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantsServer).AddRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurant_server.Restaurants/AddRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantsServer).AddRestaurant(ctx, req.(*AddRestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Restaurants_serviceDesc = grpc.ServiceDesc{
	ServiceName: "restaurant_server.Restaurants",
	HandlerType: (*RestaurantsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRestaurant",
			Handler:    _Restaurants_AddRestaurant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/restaurant_server/restaurant_server.proto",
}
