// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/metrics_server/metrics_server.proto

package metrics_server

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CalcType int32

const (
	CalcType_CALC_UNKNOWN    CalcType = 0
	CalcType_CALC_AVERAGE    CalcType = 1
	CalcType_CALC_PERCENTILE CalcType = 2
)

var CalcType_name = map[int32]string{
	0: "CALC_UNKNOWN",
	1: "CALC_AVERAGE",
	2: "CALC_PERCENTILE",
}

var CalcType_value = map[string]int32{
	"CALC_UNKNOWN":    0,
	"CALC_AVERAGE":    1,
	"CALC_PERCENTILE": 2,
}

func (x CalcType) Enum() *CalcType {
	p := new(CalcType)
	*p = x
	return p
}

func (x CalcType) String() string {
	return proto.EnumName(CalcType_name, int32(x))
}

func (x *CalcType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CalcType_value, data, "CalcType")
	if err != nil {
		return err
	}
	*x = CalcType(value)
	return nil
}

func (CalcType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f132545da4b15114, []int{0}
}

type Order struct {
	OrderId              *string  `protobuf:"bytes,1,opt,name=orderId" json:"orderId,omitempty"`
	Email                *string  `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	RestId               *string  `protobuf:"bytes,3,opt,name=restId" json:"restId,omitempty"`
	Items                []string `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_f132545da4b15114, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderId() string {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return ""
}

func (m *Order) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *Order) GetRestId() string {
	if m != nil && m.RestId != nil {
		return *m.RestId
	}
	return ""
}

func (m *Order) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

type OrderDetailsRequest struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDetailsRequest) Reset()         { *m = OrderDetailsRequest{} }
func (m *OrderDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*OrderDetailsRequest) ProtoMessage()    {}
func (*OrderDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f132545da4b15114, []int{1}
}

func (m *OrderDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetailsRequest.Unmarshal(m, b)
}
func (m *OrderDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetailsRequest.Marshal(b, m, deterministic)
}
func (m *OrderDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetailsRequest.Merge(m, src)
}
func (m *OrderDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_OrderDetailsRequest.Size(m)
}
func (m *OrderDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetailsRequest proto.InternalMessageInfo

func (m *OrderDetailsRequest) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type OrderDetailsResponse struct {
	Response             *string  `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDetailsResponse) Reset()         { *m = OrderDetailsResponse{} }
func (m *OrderDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*OrderDetailsResponse) ProtoMessage()    {}
func (*OrderDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f132545da4b15114, []int{2}
}

func (m *OrderDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetailsResponse.Unmarshal(m, b)
}
func (m *OrderDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetailsResponse.Marshal(b, m, deterministic)
}
func (m *OrderDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetailsResponse.Merge(m, src)
}
func (m *OrderDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_OrderDetailsResponse.Size(m)
}
func (m *OrderDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetailsResponse proto.InternalMessageInfo

func (m *OrderDetailsResponse) GetResponse() string {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return ""
}

// come back later to use enums
type RunMetricScrapeRequest struct {
	Time                 *string   `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	CalcType             *CalcType `protobuf:"varint,2,opt,name=calcType,enum=metrics_server.CalcType" json:"calcType,omitempty"`
	Name                 *string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Help                 *string   `protobuf:"bytes,4,opt,name=help" json:"help,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RunMetricScrapeRequest) Reset()         { *m = RunMetricScrapeRequest{} }
func (m *RunMetricScrapeRequest) String() string { return proto.CompactTextString(m) }
func (*RunMetricScrapeRequest) ProtoMessage()    {}
func (*RunMetricScrapeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f132545da4b15114, []int{3}
}

func (m *RunMetricScrapeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunMetricScrapeRequest.Unmarshal(m, b)
}
func (m *RunMetricScrapeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunMetricScrapeRequest.Marshal(b, m, deterministic)
}
func (m *RunMetricScrapeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunMetricScrapeRequest.Merge(m, src)
}
func (m *RunMetricScrapeRequest) XXX_Size() int {
	return xxx_messageInfo_RunMetricScrapeRequest.Size(m)
}
func (m *RunMetricScrapeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunMetricScrapeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunMetricScrapeRequest proto.InternalMessageInfo

func (m *RunMetricScrapeRequest) GetTime() string {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return ""
}

func (m *RunMetricScrapeRequest) GetCalcType() CalcType {
	if m != nil && m.CalcType != nil {
		return *m.CalcType
	}
	return CalcType_CALC_UNKNOWN
}

func (m *RunMetricScrapeRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *RunMetricScrapeRequest) GetHelp() string {
	if m != nil && m.Help != nil {
		return *m.Help
	}
	return ""
}

type RunMetricScrapeResponse struct {
	Response             *string  `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunMetricScrapeResponse) Reset()         { *m = RunMetricScrapeResponse{} }
func (m *RunMetricScrapeResponse) String() string { return proto.CompactTextString(m) }
func (*RunMetricScrapeResponse) ProtoMessage()    {}
func (*RunMetricScrapeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f132545da4b15114, []int{4}
}

func (m *RunMetricScrapeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunMetricScrapeResponse.Unmarshal(m, b)
}
func (m *RunMetricScrapeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunMetricScrapeResponse.Marshal(b, m, deterministic)
}
func (m *RunMetricScrapeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunMetricScrapeResponse.Merge(m, src)
}
func (m *RunMetricScrapeResponse) XXX_Size() int {
	return xxx_messageInfo_RunMetricScrapeResponse.Size(m)
}
func (m *RunMetricScrapeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunMetricScrapeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunMetricScrapeResponse proto.InternalMessageInfo

func (m *RunMetricScrapeResponse) GetResponse() string {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return ""
}

func init() {
	proto.RegisterEnum("metrics_server.CalcType", CalcType_name, CalcType_value)
	proto.RegisterType((*Order)(nil), "metrics_server.Order")
	proto.RegisterType((*OrderDetailsRequest)(nil), "metrics_server.OrderDetailsRequest")
	proto.RegisterType((*OrderDetailsResponse)(nil), "metrics_server.OrderDetailsResponse")
	proto.RegisterType((*RunMetricScrapeRequest)(nil), "metrics_server.RunMetricScrapeRequest")
	proto.RegisterType((*RunMetricScrapeResponse)(nil), "metrics_server.RunMetricScrapeResponse")
}

func init() {
	proto.RegisterFile("proto/metrics_server/metrics_server.proto", fileDescriptor_f132545da4b15114)
}

var fileDescriptor_f132545da4b15114 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x5d, 0x4b, 0xc3, 0x40,
	0x10, 0x6c, 0xfa, 0x61, 0xeb, 0x2a, 0x6d, 0xb8, 0xd6, 0x7a, 0xf4, 0xa9, 0xe4, 0xc1, 0x4f, 0xa8,
	0x10, 0xf4, 0x07, 0xb4, 0x31, 0x48, 0xb1, 0xa6, 0x72, 0x56, 0x05, 0x5f, 0x4a, 0x48, 0x16, 0x0c,
	0x24, 0x4d, 0xbc, 0xbb, 0x0a, 0xfe, 0x05, 0x7f, 0xb5, 0xe4, 0x92, 0x14, 0x1a, 0x0b, 0x7d, 0x9b,
	0x99, 0xcc, 0xed, 0xcc, 0x2e, 0x81, 0xcb, 0x84, 0xc7, 0x32, 0xbe, 0x89, 0x50, 0xf2, 0xc0, 0x13,
	0x4b, 0x81, 0xfc, 0x1b, 0x79, 0x89, 0x8e, 0x94, 0x87, 0xb4, 0xb7, 0x55, 0x03, 0xa1, 0x31, 0xe7,
	0x3e, 0x72, 0x42, 0xa1, 0x19, 0xa7, 0x60, 0xea, 0x53, 0x6d, 0xa8, 0x5d, 0x1c, 0xb2, 0x82, 0x92,
	0x1e, 0x34, 0x30, 0x72, 0x83, 0x90, 0x56, 0x95, 0x9e, 0x11, 0xd2, 0x87, 0x03, 0x8e, 0x42, 0x4e,
	0x7d, 0x5a, 0x53, 0x72, 0xce, 0x52, 0x77, 0x20, 0x31, 0x12, 0xb4, 0x3e, 0xac, 0xa5, 0x6e, 0x45,
	0x8c, 0x09, 0x74, 0x55, 0xcc, 0x3d, 0x4a, 0x37, 0x08, 0x05, 0xc3, 0xaf, 0x35, 0x0a, 0x49, 0xae,
	0xa1, 0xa1, 0x52, 0x54, 0xe4, 0x91, 0x79, 0x32, 0x2a, 0x75, 0x56, 0x6f, 0x58, 0xe6, 0x31, 0x4c,
	0xe8, 0x6d, 0xcf, 0x10, 0x49, 0xbc, 0x12, 0x48, 0x06, 0xd0, 0xe2, 0x39, 0xce, 0xab, 0x6f, 0xb8,
	0xf1, 0xab, 0x41, 0x9f, 0xad, 0x57, 0x4f, 0x6a, 0xec, 0x8b, 0xc7, 0xdd, 0x04, 0x8b, 0x6c, 0x02,
	0x75, 0x19, 0x44, 0xc5, 0x13, 0x85, 0xc9, 0x2d, 0xb4, 0x3c, 0x37, 0xf4, 0x16, 0x3f, 0x09, 0xaa,
	0x6d, 0xdb, 0x26, 0x2d, 0x57, 0xb2, 0xf2, 0xef, 0x6c, 0xe3, 0x4c, 0x27, 0xad, 0xdc, 0x08, 0xf3,
	0x43, 0x28, 0x9c, 0x6a, 0x9f, 0x18, 0x26, 0xb4, 0x9e, 0x69, 0x29, 0x36, 0xee, 0xe0, 0xf4, 0x5f,
	0x97, 0xfd, 0x3b, 0x5c, 0x59, 0xd0, 0x2a, 0x42, 0x89, 0x0e, 0xc7, 0xd6, 0x78, 0x66, 0x2d, 0x5f,
	0x9d, 0x47, 0x67, 0xfe, 0xee, 0xe8, 0x95, 0x8d, 0x32, 0x7e, 0xb3, 0xd9, 0xf8, 0xc1, 0xd6, 0x35,
	0xd2, 0x85, 0x8e, 0x52, 0x9e, 0x6d, 0x66, 0xd9, 0xce, 0x62, 0x3a, 0xb3, 0xf5, 0xaa, 0x19, 0x43,
	0x33, 0x0b, 0x16, 0xc4, 0x87, 0x4e, 0xa9, 0x06, 0x39, 0x2b, 0x6f, 0xb9, 0xfb, 0x66, 0x83, 0xf3,
	0xbd, 0xbe, 0xfc, 0xee, 0x95, 0x49, 0xff, 0xa3, 0xb7, 0xeb, 0xaf, 0xfc, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0x08, 0x84, 0x14, 0xec, 0xac, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetricsClient is the client API for Metrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetricsClient interface {
	// creates a new metrics scraper
	RunMetricScrape(ctx context.Context, in *RunMetricScrapeRequest, opts ...grpc.CallOption) (*RunMetricScrapeResponse, error)
}

type metricsClient struct {
	cc *grpc.ClientConn
}

func NewMetricsClient(cc *grpc.ClientConn) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) RunMetricScrape(ctx context.Context, in *RunMetricScrapeRequest, opts ...grpc.CallOption) (*RunMetricScrapeResponse, error) {
	out := new(RunMetricScrapeResponse)
	err := c.cc.Invoke(ctx, "/metrics_server.Metrics/RunMetricScrape", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServer is the server API for Metrics service.
type MetricsServer interface {
	// creates a new metrics scraper
	RunMetricScrape(context.Context, *RunMetricScrapeRequest) (*RunMetricScrapeResponse, error)
}

// UnimplementedMetricsServer can be embedded to have forward compatible implementations.
type UnimplementedMetricsServer struct {
}

func (*UnimplementedMetricsServer) RunMetricScrape(ctx context.Context, req *RunMetricScrapeRequest) (*RunMetricScrapeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunMetricScrape not implemented")
}

func RegisterMetricsServer(s *grpc.Server, srv MetricsServer) {
	s.RegisterService(&_Metrics_serviceDesc, srv)
}

func _Metrics_RunMetricScrape_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunMetricScrapeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).RunMetricScrape(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrics_server.Metrics/RunMetricScrape",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).RunMetricScrape(ctx, req.(*RunMetricScrapeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Metrics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metrics_server.Metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunMetricScrape",
			Handler:    _Metrics_RunMetricScrape_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/metrics_server/metrics_server.proto",
}
