mongo:
  mongo_server: 'mongodb://localhost:27017'
  database: 'chefcurrygobbles'
  collections:
    users: 'Users'
    restaurants: 'Restaurants'
    orders: 'Orders'

server:
  network: 'tcp'
  address: ':50051'